// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0I-kCgXH36yuXnduKUzN3-LqXVV-Hu-s',
    appId: '1:164827328009:web:0a6f235334ea26b975d2d8',
    messagingSenderId: '164827328009',
    projectId: 'expenses-58086',
    authDomain: 'expenses-58086.firebaseapp.com',
    storageBucket: 'expenses-58086.appspot.com',
    measurementId: 'G-1M4GYGJ9TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJhTiYNb_lZNLu-AVs5KpaKhR1I3qI2zk',
    appId: '1:164827328009:android:d91ff2818322557f75d2d8',
    messagingSenderId: '164827328009',
    projectId: 'expenses-58086',
    storageBucket: 'expenses-58086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmpL-JqjAkmqWSuIBezmc43JJV0MKpxs',
    appId: '1:164827328009:ios:1912621bc1b0565375d2d8',
    messagingSenderId: '164827328009',
    projectId: 'expenses-58086',
    storageBucket: 'expenses-58086.appspot.com',
    iosBundleId: 'com.example.expenseControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmpL-JqjAkmqWSuIBezmc43JJV0MKpxs',
    appId: '1:164827328009:ios:1912621bc1b0565375d2d8',
    messagingSenderId: '164827328009',
    projectId: 'expenses-58086',
    storageBucket: 'expenses-58086.appspot.com',
    iosBundleId: 'com.example.expenseControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0I-kCgXH36yuXnduKUzN3-LqXVV-Hu-s',
    appId: '1:164827328009:web:aac1d70bf01f0fbb75d2d8',
    messagingSenderId: '164827328009',
    projectId: 'expenses-58086',
    authDomain: 'expenses-58086.firebaseapp.com',
    storageBucket: 'expenses-58086.appspot.com',
    measurementId: 'G-T5J9KK9DNL',
  );
}
